# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simple_pb2 as simple__pb2


class SimpleServiceStub(object):
    """interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleSend = channel.unary_unary(
                '/simple.SimpleService/SimpleSend',
                request_serializer=simple__pb2.SimpleRequestList.SerializeToString,
                response_deserializer=simple__pb2.SimpleResponseList.FromString,
                )


class SimpleServiceServicer(object):
    """interface
    """

    def SimpleSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleSend': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleSend,
                    request_deserializer=simple__pb2.SimpleRequestList.FromString,
                    response_serializer=simple__pb2.SimpleResponseList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simple.SimpleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleService(object):
    """interface
    """

    @staticmethod
    def SimpleSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simple.SimpleService/SimpleSend',
            simple__pb2.SimpleRequestList.SerializeToString,
            simple__pb2.SimpleResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
